[context.production.environment]
  JEKYLL_ENV = "production"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"

[[redirects]]
  from = "/"
  to = "/introduction/what-is-finops"
  status = 302
  force = true