backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored here

collections:
  - name: 'capabilities'
    label: 'Capabilities'
    folder: '_capabilities/'
    create: false
    hide: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "capability"}
      - {label: "Meta Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Ientifier", name: "page-identifier", widget: "string"}
      - {label: "capability Title", name: "framework-capability-title", widget: "string"}
      - {label: "capability Description", name: "framework-capability-desc", widget: "string"}
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'Data'
    label: 'Data'
    editor:
      preview: false
    files: 
      - label: 'Industry'
        name: 'industry' 
        file: '_data/industry.yml'
        fields: 
          - label: "Location Items"
            name: "items"
            widget: "list"
            fields: 
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Identifier", name: "identifier", widget: "string"}
  - name: "stories" 
    label: "Stories" 
    folder: "_stories" 
    create: true 
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "story"}
      - {label: "Meta Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Story Title", name: "story-title", widget: "string"}
      - {label: "Date", name: "story-date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {
          label: "Cloud Provider",
          name: "cloud-provider",
          widget: "select",
          multiple: true,
          options: ["AWS", "GCP", "AZURE", "ALIBABA", "TENCENT"]
        }
      - {
          label: "Maturity",
          name: "framework-maturity",
          widget: "select",
          options: ["Crawl", "Walk", "Run"]
        }
      - {
          label: "Capabilities",
          name: "framework-capabilities",
          widget: "relation",
          collection: "capabilities",
          search_fields: ["framework-capability-title"],
          value_field: "page-identifier",
          multiple: true,
          display_fields: ["framework-capability-title"]
        }
      - {
          label: "Industry",
          name: "industry",
          widget: "relation",
          collection: "industry",
          search_fields: ["industry.name"],
          value_field: "industry.identifier",
          multiple: true,
          display_fields: ["industry.name"]
        }
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}