backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored here

collections:
  - name: 'capabilities'
    label: 'Capabilities'
    folder: '_capabilities/'
    create: false
    hide: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "capability"}
      - {label: "Meta Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Ientifier", name: "page-identifier", widget: "string"}
      - {label: "Capability Title", name: "framework-capability-title", widget: "string"}
      - {label: "Capability Description", name: "framework-capability-desc", widget: "string"}
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    create: false
    hide: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "wide"}
      - {label: "Meta Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Identifier", name: "page-identifier", widget: "string"}
      - {label: "Project Title", name: "project-title", widget: "string"}
      - {label: "Project Description", name: "project-description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "stories" 
    label: "Stories" 
    folder: "_stories" 
    create: true 
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "story"}
      - {label: "Meta Title", name: "title", widget: "string"}
      - {label: "Meta Description", name: "description", widget: "string"}
      - {label: "Story Title", name: "story-title", widget: "string"}
      - {label: "Date", name: "story-date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {
          label: "Cloud Provider",
          name: "cloud-provider",
          widget: "select",
          multiple: true,
          options: ["AWS", "GCP", "AZURE", "ALIBABA", "TENCENT"]
        }
      - {
          label: "Maturity",
          name: "framework-maturity",
          widget: "select",
          options: ["Crawl", "Walk", "Run"]
        }
      - {
          label: "Capabilities",
          name: "framework-capabilities",
          widget: "relation",
          collection: "capabilities",
          search_fields: ["framework-capability-title"],
          value_field: "page-identifier",
          multiple: true,
          display_fields: ["framework-capability-title"]
        }
      - {
          label: "Projects",
          name: "framework-projects",
          widget: "relation",
          collection: "projects",
          search_fields: ["project-title"],
          value_field: "page-identifier",
          multiple: true,
          display_fields: ["project-title"],
          required: false
        }
      - {
          label: "Industry",
          name: "industry",
          widget: "select",
          multiple: true,
          options: ["Automotive", "Business Services", "Consumer Packaged Goods", "Construction/Engineering", "Education", "Higher Education", "Energy", "Financial Services", "Government", "Local Government", "Health Care", "Information Technology", "Life Sciences", "Manufacturing", "Media", "Oil & Gas", "Professional Services", "Retail & Wholesale", "Telecommunications / Internet Service Provider", "Transportation & Logistics", "Utilities"],
          required: false
        }
      - {
          label: "Persona",
          name: "framework-persona",
          widget: "select",
          multiple: true,
          options: ["FinOps Practitioner", "Executive", "Engineering and Operations", "Finance", "Procurement", "Product Owner", "Business Owner"],
          required: false
        }
      - {label: "Order", name: "order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown"}